include("${REPO_ROOT}/cmake/PerastageWindowsVcpkgResolver.cmake")

unset(ENV{VCPKG_ROOT})
unset(ENV{LOCALAPPDATA})
unset(ENV{APPDATA})

if(CASE STREQUAL "explicit-external")
    set(ENV{VCPKG_ROOT} "${EXTERNAL_ROOT}")
    set(ENV{LOCALAPPDATA} "${USER_CONFIG_ROOT}")
elseif(CASE STREQUAL "visual-studio-override")
    set(ENV{VCPKG_ROOT} "C:/Program Files/Microsoft Visual Studio/18/Community/VC/vcpkg")
    set(ENV{LOCALAPPDATA} "${USER_CONFIG_ROOT}")
elseif(CASE STREQUAL "user-wide-only" OR CASE STREQUAL "bootstrap-user-wide")
    set(ENV{LOCALAPPDATA} "${USER_CONFIG_ROOT}")
elseif(CASE STREQUAL "appdata-only")
    set(ENV{APPDATA} "${USER_CONFIG_ROOT}")
elseif(CASE STREQUAL "stale-descriptor")
    set(ENV{LOCALAPPDATA} "${STALE_CONFIG_ROOT}")
elseif(CASE STREQUAL "bundled-descriptor")
    set(ENV{LOCALAPPDATA} "${BUNDLED_CONFIG_ROOT}")
elseif(NOT CASE STREQUAL "both-missing")
    message(FATAL_ERROR "Unknown Windows vcpkg resolver fixture case: ${CASE}")
endif()

if(CASE STREQUAL "bootstrap-user-wide")
    include("${REPO_ROOT}/cmake/PerastageWindowsVcpkgToolchain.cmake")
    file(WRITE "${RESULT_FILE}"
        "${PERASTAGE_RESOLVED_VCPKG_ROOT}|$ENV{VCPKG_ROOT}|${SYNTHETIC_TOOLCHAIN_INCLUDED}")
else()
    perastage_resolve_windows_vcpkg_root(resolved_root)
    file(WRITE "${RESULT_FILE}" "${resolved_root}")
endif()
