include("${REPO_ROOT}/cmake/PerastageWindowsVcpkgGuard.cmake")

set(VCPKG_TARGET_TRIPLET "x64-windows")
set(VCPKG_MANIFEST_MODE "OFF")
set(VCPKG_MANIFEST_INSTALL "OFF")

if(CASE STREQUAL "missing-root")
    unset(ENV{VCPKG_ROOT})
    set(CMAKE_TOOLCHAIN_FILE "/scripts/buildsystems/vcpkg.cmake")
elseif(CASE STREQUAL "bundled-visual-studio")
    set(ENV{VCPKG_ROOT} "${VCPKG_ROOT_FIXTURE}")
    set(CMAKE_TOOLCHAIN_FILE "C:/Program Files/Microsoft Visual Studio/18/Community/VC/vcpkg/scripts/buildsystems/vcpkg.cmake")
elseif(CASE STREQUAL "mismatched-root")
    set(ENV{VCPKG_ROOT} "${VCPKG_ROOT_FIXTURE}")
    set(CMAKE_TOOLCHAIN_FILE "${VCPKG_ROOT_FIXTURE}/other/scripts/buildsystems/vcpkg.cmake")
elseif(CASE STREQUAL "valid-root")
    set(ENV{VCPKG_ROOT} "${VCPKG_ROOT_FIXTURE}")
    set(CMAKE_TOOLCHAIN_FILE "${VCPKG_ROOT_FIXTURE}/scripts/buildsystems/vcpkg.cmake")
else()
    message(FATAL_ERROR "Unknown Windows vcpkg guard fixture case: ${CASE}")
endif()

perastage_validate_windows_classic_vcpkg(TRUE)
