cmake_minimum_required(VERSION 3.21)
include("${REPO_ROOT}/cmake/PerastageGitBashResolver.cmake")
set(ENV{PATH} "")
if(CASE_MODE STREQUAL "invalid-explicit")
    set(BASH_EXECUTABLE "${CMAKE_CURRENT_LIST_DIR}/definitely-missing-bash.exe" CACHE FILEPATH "" FORCE)
else()
    unset(BASH_EXECUTABLE CACHE)
    unset(BASH_EXECUTABLE)
endif()
if(WIN32)
    perastage_resolve_git_bash(_resolved FORCE_WINDOWS REQUIRED_FOR_TESTING)
else()
    perastage_resolve_git_bash(_resolved REQUIRED_FOR_TESTING)
endif()
