#include "gdtf/fixture_symbol_comparison_panel.h"

#include <algorithm>
#include <memory>
#include <wx/dcbuffer.h>
#include <wx/sizer.h>
#include <wx/statbox.h>
#include <wx/stattext.h>
#include "symbols/fixture_symbol_availability.h"
#include "windows/symbol_preview_drawing.h"

namespace {
wxString ProvenanceLabel(FixtureSymbolProvenance provenance) {
  switch (provenance) {
  case FixtureSymbolProvenance::AuthoredGdtf: return _("Authored GDTF");
  case FixtureSymbolProvenance::GeneratedPerastage: return _("Generated by Perastage");
  case FixtureSymbolProvenance::LegacyPerastage: return _("Legacy Perastage");
  default: return _("N/A");
  }
}
}

FixtureSymbolComparisonPanel::FixtureSymbolComparisonPanel(wxWindow *parent)
    : wxPanel(parent) {
  auto *root = new wxBoxSizer(wxVERTICAL);
  SetSizer(root);
  for (auto set : {FixtureSymbolResourceSet::StandardGdtf, FixtureSymbolResourceSet::Perastage}) {
    auto *group = new wxStaticBoxSizer(wxHORIZONTAL, this,
        set == FixtureSymbolResourceSet::StandardGdtf ? _("Standard GDTF") : _("Perastage"));
    const auto add = [&](SymbolViewKind view, const wxString &label) {
      auto *column = new wxBoxSizer(wxVERTICAL);
      column->Add(new wxStaticText(group->GetStaticBox(), wxID_ANY, label),
                  0, wxALIGN_CENTER_HORIZONTAL | wxBOTTOM, 3);
      auto *panel = new wxPanel(group->GetStaticBox(), wxID_ANY, wxDefaultPosition,
                               wxSize(70, 70), wxBORDER_SIMPLE);
      panel->SetBackgroundStyle(wxBG_STYLE_PAINT);
      panel->Bind(wxEVT_PAINT, &FixtureSymbolComparisonPanel::DrawPreview, this);
      panel->Bind(wxEVT_SIZE, [panel](wxSizeEvent &event) { panel->Refresh(); event.Skip(); });
      previews_.push_back({panel, set, view, {}, {}});
      column->Add(panel, 1, wxEXPAND);
      group->Add(column, 1, wxEXPAND | wxALL, 3);
    };
    add(SymbolViewKind::Top, _("Top"));
    add(SymbolViewKind::Front, _("Front"));
    add(SymbolViewKind::Left, _("Side"));
    if (set == FixtureSymbolResourceSet::Perastage)
      add(SymbolViewKind::Bottom, _("Bottom"));
    root->Add(group, 1, wxEXPAND | wxALL, 6);
  }
}

void FixtureSymbolComparisonPanel::SetArchivePath(const std::string &path) {
  const auto availability = symbol_cache::InspectFixtureSymbolAvailability(path);
  for (auto &preview : previews_) {
    preview.model = BuildFixtureSymbolPreviewModel(availability.resources, preview.set, preview.view);
    preview.data.reset();
    std::string diagnostic = preview.model.resource.diagnostic;
    if (preview.model.available) {
      preview.data = symbol_cache::LoadUsableFixtureSymbol(path, preview.view, &diagnostic,
                                                          preview.model.purpose);
      if (preview.data && (preview.data->sourcePath != preview.model.resource.archivePath ||
          preview.data->resourceSet != preview.set || preview.data->viewKind != preview.view ||
          preview.data->usedViewFallback))
        preview.data.reset();
      if (diagnostic.empty())
        diagnostic = preview.model.resource.diagnostic;
    }
    preview.panel->SetToolTip(wxString::Format(_("Archive path: %s\nProvenance: %s\nDiagnostic: %s"),
        wxString::FromUTF8(preview.model.resource.archivePath),
        ProvenanceLabel(preview.model.resource.provenance), wxString::FromUTF8(diagnostic)));
    preview.panel->Refresh();
  }
}

void FixtureSymbolComparisonPanel::DrawPreview(wxPaintEvent &event) {
  const auto it = std::find_if(previews_.begin(), previews_.end(), [&](const auto &preview) {
    return preview.panel == event.GetEventObject();
  });
  if (it == previews_.end())
    return;
  wxAutoBufferedPaintDC dc(it->panel);
  dc.SetBackground(wxBrush(it->panel->GetBackgroundColour()));
  dc.Clear();
  const wxRect rect = it->panel->GetClientRect();
  if (!it->data) {
    dc.DrawLabel(_("N/A"), rect, wxALIGN_CENTER);
    return;
  }
  symbol_preview::DrawTransparencyBackground(dc, rect);
  std::unique_ptr<wxGraphicsContext> gc(wxGraphicsContext::Create(dc));
  if (!gc)
    return;
  const auto &svg = *it->data;
  const double scale = std::max(0.0, std::min((rect.GetWidth() - 8.0) / std::max(1.0, svg.viewBoxWidth),
                                           (rect.GetHeight() - 8.0) / std::max(1.0, svg.viewBoxHeight)));
  const double originX = (rect.GetWidth() - svg.viewBoxWidth * scale) * 0.5;
  const double originY = (rect.GetHeight() - svg.viewBoxHeight * scale) * 0.5;
  const auto transform = [&](const auto &point) {
    return wxPoint2DDouble(originX + point.x * scale, originY + point.y * scale);
  };
  gc->SetPen(*wxTRANSPARENT_PEN);
  gc->SetBrush(wxBrush(wxColour(224, 224, 224)));
  for (const auto &polygon : svg.fills) {
    if (polygon.points.size() < 3)
      continue;
    auto path = gc->CreatePath();
    symbol_preview::AppendPreviewRing(path, polygon.points, transform);
    for (const auto &hole : polygon.holes)
      symbol_preview::AppendPreviewRing(path, hole, transform);
    gc->FillPath(path, wxODDEVEN_RULE);
  }
  gc->SetPen(wxPen(*wxBLACK, 1));
  for (const auto &line : svg.strokes) {
    if (line.points.size() < 2)
      continue;
    auto path = gc->CreatePath();
    const auto first = transform(line.points.front());
    path.MoveToPoint(first.m_x, first.m_y);
    for (std::size_t i = 1; i < line.points.size(); ++i) {
      const auto point = transform(line.points[i]);
      path.AddLineToPoint(point.m_x, point.m_y);
    }
    gc->StrokePath(path);
  }
}
