function(perastage_reject_quoted_path_value variable_name)
    if(NOT DEFINED ${variable_name})
        return()
    endif()
    set(_value "${${variable_name}}")
    if(_value MATCHES "^\"|\"$")
        message(FATAL_ERROR "${variable_name} contains literal double-quote characters: ${_value}")
    endif()
endfunction()

function(perastage_reject_quoted_path_values)
    foreach(_variable_name IN LISTS ARGN)
        perastage_reject_quoted_path_value(${_variable_name})
    endforeach()
endfunction()
