if(NOT DEFINED PDB_SOURCE OR NOT DEFINED PDB_DESTINATION)
    message(FATAL_ERROR "PDB_SOURCE and PDB_DESTINATION must be defined.")
endif()

if(EXISTS "${PDB_SOURCE}")
    file(MAKE_DIRECTORY "${PDB_DESTINATION}")
    file(COPY "${PDB_SOURCE}" DESTINATION "${PDB_DESTINATION}")
endif()
